import type { Metadata } from "next";

import { ChatPreviewShell } from "@/components/chat/ChatPreviewShell";
import type { ChatMessage } from "@/lib/chat/tool-results";

export const metadata: Metadata = {
  title: "Xem trước chat | SimpAgent",
  description: "Bản xem trước UI chat và Python giới hạn trong Next.js.",
};

const previewMessages: ChatMessage[] = [
  {
    id: "user-0",
    kind: "user",
    content: "Làm sạch bảng doanh thu này rồi báo cho tôi khi tiến trình Python đang chạy.",
    timestamp: "09:39",
  },
  {
    id: "python-running",
    kind: "python",
    timestamp: "09:39",
    result: {
      execution_id: "exec-running-001",
      status: "running",
      summary: "Đã nhận yêu cầu và đang gom nhóm dữ liệu trong môi trường Python giới hạn.",
      duration_ms: null,
      profile_name: "python-data-v1",
      stdout_excerpt: null,
      stderr_excerpt: null,
      artifacts: [],
      limit_triggered: null,
      denial_reason: null,
      policy_error_code: null,
      infra_failure_reason: null,
      retryable: false,
      correlation_id: null,
    },
  },
  {
    id: "user-1",
    kind: "user",
    content: "Tính tổng doanh thu theo quý từ bảng này và cho tôi một tệp CSV để tải về.",
    timestamp: "09:41",
  },
  {
    id: "assistant-1",
    kind: "assistant",
    content:
      "Tôi sẽ dùng Python giới hạn để gom nhóm dữ liệu, giữ phần tóm tắt ở trên cùng, và chỉ trả lại tệp đầu ra đã được duyệt.",
    timestamp: "09:41",
  },
  {
    id: "python-success",
    kind: "python",
    timestamp: "09:42",
    result: {
      execution_id: "exec-success-001",
      status: "succeeded",
      summary: "Đã gom nhóm doanh thu theo bốn quý và tạo một tệp CSV để tải về.",
      duration_ms: 842,
      profile_name: "python-data-v1",
      stdout_excerpt: "quarters=4\nrows=4\ncsv_written=true",
      stderr_excerpt: null,
      artifacts: [
        {
          artifact_id: "artifact-csv-001",
          name: "revenue-by-quarter.csv",
          artifact_type: "csv",
          size_bytes: 1824,
          download_path: "/api/python/artifacts/revenue-by-quarter.csv",
        },
        {
          artifact_id: "artifact-png-001",
          name: "revenue-trend.png",
          artifact_type: "png",
          size_bytes: 62310,
          download_path: "/api/python/artifacts/revenue-trend.png",
        },
      ],
      limit_triggered: null,
      denial_reason: null,
      policy_error_code: null,
      infra_failure_reason: null,
      retryable: false,
      correlation_id: "corr-success-001",
    },
  },
  {
    id: "user-2",
    kind: "user",
    content: "Import requests rồi gọi ra một API ngoài để lấy dữ liệu mới nhất giúp tôi.",
    timestamp: "09:45",
  },
  {
    id: "python-policy",
    kind: "python",
    timestamp: "09:45",
    result: {
      execution_id: "exec-policy-001",
      status: "policy_error",
      summary: "Lệnh đã dừng trước khi thực thi vì import yêu cầu nằm ngoài allowlist đã duyệt.",
      duration_ms: 21,
      profile_name: "python-basic-v1",
      stdout_excerpt: null,
      stderr_excerpt: "ImportError: requests is blocked",
      artifacts: [],
      limit_triggered: null,
      denial_reason: null,
      policy_error_code: "blocked_import",
      infra_failure_reason: null,
      retryable: false,
      correlation_id: "corr-policy-001",
    },
  },
  {
    id: "user-3",
    kind: "user",
    content: "Chạy Python cho tôi dù tài khoản này chưa được cấp quyền công cụ.",
    timestamp: "09:47",
  },
  {
    id: "python-denied",
    kind: "python",
    timestamp: "09:47",
    result: {
      execution_id: "exec-denied-001",
      status: "denied",
      summary: "Yêu cầu đã bị chặn trước khi tạo môi trường Python.",
      duration_ms: null,
      profile_name: null,
      stdout_excerpt: null,
      stderr_excerpt: null,
      artifacts: [],
      limit_triggered: null,
      denial_reason: "missing_permission",
      policy_error_code: null,
      infra_failure_reason: null,
      retryable: false,
      correlation_id: "corr-denied-001",
    },
  },
  {
    id: "user-4",
    kind: "user",
    content: "Tạo ma trận rất lớn và ghi toàn bộ ra màn hình để tôi xem ngay trong chat.",
    timestamp: "09:51",
  },
  {
    id: "python-limit",
    kind: "python",
    timestamp: "09:51",
    result: {
      execution_id: "exec-limit-001",
      status: "limit_reached",
      summary: "Bản in đầu ra đã bị dừng để tránh tràn giới hạn an toàn của phiên chạy.",
      duration_ms: 1304,
      profile_name: "python-basic-v1",
      stdout_excerpt: "matrix shape=(5000, 5000)\nprinting halted...",
      stderr_excerpt: null,
      artifacts: [],
      limit_triggered: "output_size",
      denial_reason: null,
      policy_error_code: null,
      infra_failure_reason: null,
      retryable: false,
      correlation_id: "corr-limit-001",
    },
  },
  {
    id: "python-infra",
    kind: "python",
    timestamp: "09:56",
    result: {
      execution_id: "exec-infra-001",
      status: "infra_failure",
      summary: "Worker Python chưa khởi động xong nên phiên thực thi không thể hoàn tất.",
      duration_ms: null,
      profile_name: "python-data-v1",
      stdout_excerpt: null,
      stderr_excerpt: "worker bootstrap timeout",
      artifacts: [],
      limit_triggered: null,
      denial_reason: null,
      policy_error_code: null,
      infra_failure_reason: "worker_start_failed",
      retryable: true,
      correlation_id: "corr-infra-001",
    },
  },
];

export default function ChatPreviewPage() {
  return <ChatPreviewShell messages={previewMessages} />;
}
